name: spa
description: Solar Position Algorithm used for finding the orientation of the sun at any point on earth.
version: 1.2.0
homepage: https://github.com/PixelToast/dart-spa
author: Andre Lipke <andre.lipke@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  tuple: ^2.0.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7