name: cities
description: Cities example for the spa plugin
version: 1.0.0
homepage: https://github.com/PixelToast/dart-spa
author: Andre Lipke <andre.lipke@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  timezone: ^0.5.4
  spa:
    path: ../../

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0