name: cities
description: Cities example for the spa plugin
version: 1.0.0
homepage: https://github.com/PixelToast/dart-spa
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  timezone: ^0.7.0-nullsafety.0
  spa:
    path: ../../

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7